# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170711_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
