# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170714_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
