# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170714_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
