# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170720_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_score',
            field=models.FloatField(default=0),
        ),
    ]
