# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170725_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
