# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0002_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
