# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0002_auto_20170713_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finalTime',
            field=models.CharField(max_length=16),
        ),
    ]
