# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0004_auto_20170715_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cheat',
            field=models.BooleanField(default=False),
        ),
    ]
