# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0005_auto_20170705_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='false_coin',
            new_name='falseCoin',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='final_score',
            new_name='finalScore',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_number',
            new_name='gameNumber',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_type',
            new_name='gameType',
        ),
    ]
