# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0006_game_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-score']},
        ),
    ]
