# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0007_auto_20170720_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-score', 'date']},
        ),
    ]
